version: "3"

services:
  app:
    build:
      context: "jira"
      args:
        JIRA_VERSION: ${JIRA_VERSION}
        IMAGE_PREFIX: ${IMAGE_PREFIX:-''}
    image: xsharp/jira:${JIRA_VERSION}
    container_name: jira-app
    hostname: "jiraapp"
    working_dir: "/opt/atlassian/jira"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ../data/jira:/var/atlassian/application-data/jira
    restart: always
    env_file:
      - ./.env
    environment:
      - TZ='Asia/Shanghai'
      - JVM_MINIMUM_MEMORY=${JVM_MINIMUM_MEMORY}
      - JVM_MAXIMUM_MEMORY=${JVM_MAXIMUM_MEMORY}
      - JVM_RESERVED_CODE_CACHE_SIZE=${JVM_RESERVED_CODE_CACHE_SIZE}

      # - ATL_PROXY_NAME=${ATL_PROXY_NAME}
      # - ATL_PROXY_PORT=${ATL_PROXY_PORT}
      # - ATL_TOMCAT_SCHEME=${ATL_TOMCAT_SCHEME}
      # - ATL_TOMCAT_SECURE=${ATL_TOMCAT_SECURE}
        
      # - HTTP_PROXY=${HTTP_PROXY}
      # - HTTPS_PROXY=${HTTPS_PROXY}
      # - NO_PROXY=${NO_PROXY}
    networks:
      - jira

  db:
    image: mysql:${MYSQL_VERSION}
    container_name: jira-mysql
    hostname: "jiramysql"
    environment:
      - TZ='Asia/Shanghai'
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_bin',
        '--transaction-isolation=READ-COMMITTED',
        '--innodb_log_file_size=256M',
        '--max_allowed_packet=256M',
        '--log_bin_trust_function_creators=1',
        '--skip-log-bin'
      ]
    volumes:
      - ../data/mysql:/var/lib/mysql
    restart: always
    networks:
      - jira

networks:
  jira:
    driver: bridge
